
POST localhost:8000/analysis
Content-Type: application/json

{
  "content": "행복한 일기 나는 불행해.. 흑흑"
}

###

POST https://8dbe-211-244-225-211.ngrok-free.app/analysis
Content-Type: application/json

{
  "content": "^_ㅁㄴ"
}